### ISSUE TITLE
Are all the answers the same #?

### ISSUE THREAD

**Issue by mikeyroth** [mykle1/MMM-ATM#1]
i have installed this module, and it seems to be working fine, but it appears all answers are #3   is this correct, or have I not been watching long enough?  Is there a way to randomize, or is this just a list.    Very new to raspberry pi, magic mirror, and github, so forgive me if this is an odd issue.

Thanks for doing this module  My wife loves trivia

**Comment by mykle1** [comment]
You are absolutely right. I wrote this quite a while ago and didn't think anyone was using it. For now, you can choose "multipleChoice: "No"," in your config entry. I will take a look at this when and if I have the time. If your wife likes trivia, you can try my MMM-JEOPARDY  module. I think it's a better module.

**Comment by mikeyroth** [comment]
Thanks for the suggestion!   I will look into it
